### ISSUE TITLE
能添加google邮箱吗

### ISSUE THREAD

**Issue by hecoter** [redrose2100/caterpillar_mail#1]
另外希望能支持传输图片和文件

**Comment by redrose2100** [comment]
### 更新
```bash
pip install -U caterpillar_mail==1.1.0
```
### 使用参考：
https://pypi.org/project/caterpillar-mail/1.1.0/

### 备注：
发送邮件带附件功能已验证过，谷歌邮箱因为个人没有谷歌邮箱，国内也没找到渠道注册，所以只是从理论上支持了，没有验证，期待验证若通过能回复告知一声，若有问题，可以继续提issue，最好能提供一些错误信息之类的，谢谢
