### ISSUE TITLE
建议：接收邮件增加“按时间过滤”

### ISSUE THREAD

**Issue by photkey** [redrose2100/caterpillar_mail#3]
作为一个python萌新，首先非常感谢你的这个开源项目，简直不要太方便了！
建议接收邮件 增加一个“按时间过滤”，在用邮箱接收验证码时，一般都是要验证一下时间是不是在有效时段内（个人经验），如果能支持按时间过滤的话，应该要方便很多。

**Comment by redrose2100** [comment]
已支持：
pip install -U caterpillar_mail==1.1.2

用法参考： [Python发送接收解析邮件caterpillar_mail使用指导文档](http://redrose2100.com/2021/12/12/Python%E5%8F%91%E9%80%81%E6%8E%A5%E6%94%B6%E8%A7%A3%E6%9E%90%E9%82%AE%E4%BB%B6caterpillar-mail%E4%BD%BF%E7%94%A8%E6%8C%87%E5%AF%BC%E6%96%87%E6%A1%A3/)  中的3.2.6

如下，时间按照如下格式填写，before不填时默认为当前时间，after不填时默认为查找所有邮箱
```python
from caterpillar_mail import Email

email=Email(username="redrose2100@163.com",auth_code="XTSDDxxxxxxZBIO")
obj = email.get_latest_email(before="2021-12-12 12:12:12",after="2021-12-11 11:11:11")
print(obj.from_name)   # 发件人名字
print(obj.from_addr)   # 发件人邮箱
print(obj.to_name)     # 收件人名字
print(obj.to_addr)     # 收件人邮箱
print(obj.date)        # 邮件时间
print(obj.subject)     # 邮件标题
print(obj.context)     # 邮件内容
```

非常感谢提出宝贵的建议，欢迎访问关注我的个人网站   http://redrose2100.com/
